# Command aliases
[alias]
# Run `build-rbmc` to build
build-rbmc = "run -p build-rbmc"
install-rbmc = "run -p build-rbmc -- --install"
# Run `build-rbmc --uninstall` to uninstall
uninstall-rbmc = "run -p build-rbmc -- --uninstall"

# Path for RBMC, retrieved by `env!()`
[env]
# Path to the repository root
REPO_ROOT = {value = "", relative = true}
# Path to build in `target`, including `bin` and `lib`
RBMC_BUILD_ROOT = {value = "target/rbmc", relative = true}